package com.dating;

import com.dating.models.PostalInfo;
import com.dating.repositories.UserRepository;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;

@SpringBootApplication
public class DatingApplication
{
    // 2560 == id_postal_info på NULL postInfo-obj. i db
    
    public static void main(String[] args)
    {
        
        SpringApplication.run(DatingApplication.class, args);
        UserRepository us = new UserRepository();
        //us.writePictureToDb(6);
        // us.readPictureFromDb(14,"testpicture2.jpg");
    }
    
    // TODO fjern evt.
    private static void postnumre()
    {
        
        ArrayList<PostalInfo> list = new ArrayList<>();
        
        
        
        list.add(new PostalInfo(	1000	,"	København K	"));
        list.add(new PostalInfo(	1001	,"	København K	"));
        list.add(new PostalInfo(	1002	,"	København K	"));
        list.add(new PostalInfo(	1003	,"	København K	"));
        list.add(new PostalInfo(	1004	,"	København K	"));
        list.add(new PostalInfo(	1005	,"	København K	"));
        list.add(new PostalInfo(	1006	,"	København K	"));
        list.add(new PostalInfo(	1007	,"	København K	"));
        list.add(new PostalInfo(	1008	,"	København K	"));
        list.add(new PostalInfo(	1009	,"	København K	"));
        list.add(new PostalInfo(	1010	,"	København K	"));
        list.add(new PostalInfo(	1011	,"	København K	"));
        list.add(new PostalInfo(	1012	,"	København K	"));
        list.add(new PostalInfo(	1013	,"	København K	"));
        list.add(new PostalInfo(	1014	,"	København K	"));
        list.add(new PostalInfo(	1015	,"	København K	"));
        list.add(new PostalInfo(	1016	,"	København K	"));
        list.add(new PostalInfo(	1017	,"	København K	"));
        list.add(new PostalInfo(	1018	,"	København K	"));
        list.add(new PostalInfo(	1019	,"	København K	"));
        list.add(new PostalInfo(	1020	,"	København K	"));
        list.add(new PostalInfo(	1021	,"	København K	"));
        list.add(new PostalInfo(	1022	,"	København K	"));
        list.add(new PostalInfo(	1023	,"	København K	"));
        list.add(new PostalInfo(	1024	,"	København K	"));
        list.add(new PostalInfo(	1025	,"	København K	"));
        list.add(new PostalInfo(	1026	,"	København K	"));
        list.add(new PostalInfo(	1045	,"	København K	"));
        list.add(new PostalInfo(	1050	,"	København K	"));
        list.add(new PostalInfo(	1051	,"	København K	"));
        list.add(new PostalInfo(	1052	,"	København K	"));
        list.add(new PostalInfo(	1053	,"	København K	"));
        list.add(new PostalInfo(	1054	,"	København K	"));
        list.add(new PostalInfo(	1055	,"	København K	"));
        list.add(new PostalInfo(	1056	,"	København K	"));
        list.add(new PostalInfo(	1057	,"	København K	"));
        list.add(new PostalInfo(	1058	,"	København K	"));
        list.add(new PostalInfo(	1059	,"	København K	"));
        list.add(new PostalInfo(	1060	,"	København K	"));
        list.add(new PostalInfo(	1061	,"	København K	"));
        list.add(new PostalInfo(	1062	,"	København K	"));
        list.add(new PostalInfo(	1063	,"	København K	"));
        list.add(new PostalInfo(	1064	,"	København K	"));
        list.add(new PostalInfo(	1065	,"	København K	"));
        list.add(new PostalInfo(	1066	,"	København K	"));
        list.add(new PostalInfo(	1067	,"	København K	"));
        list.add(new PostalInfo(	1068	,"	København K	"));
        list.add(new PostalInfo(	1069	,"	København K	"));
        list.add(new PostalInfo(	1070	,"	København K	"));
        list.add(new PostalInfo(	1071	,"	København K	"));
        list.add(new PostalInfo(	1072	,"	København K	"));
        list.add(new PostalInfo(	1073	,"	København K	"));
        list.add(new PostalInfo(	1074	,"	København K	"));
        list.add(new PostalInfo(	1092	,"	København K	"));
        list.add(new PostalInfo(	1093	,"	København K	"));
        list.add(new PostalInfo(	1095	,"	København K	"));
        list.add(new PostalInfo(	1098	,"	København K	"));
        list.add(new PostalInfo(	1100	,"	København K	"));
        list.add(new PostalInfo(	1101	,"	København K	"));
        list.add(new PostalInfo(	1102	,"	København K	"));
        list.add(new PostalInfo(	1103	,"	København K	"));
        list.add(new PostalInfo(	1104	,"	København K	"));
        list.add(new PostalInfo(	1105	,"	København K	"));
        list.add(new PostalInfo(	1106	,"	København K	"));
        list.add(new PostalInfo(	1107	,"	København K	"));
        list.add(new PostalInfo(	1110	,"	København K	"));
        list.add(new PostalInfo(	1111	,"	København K	"));
        list.add(new PostalInfo(	1112	,"	København K	"));
        list.add(new PostalInfo(	1113	,"	København K	"));
        list.add(new PostalInfo(	1114	,"	København K	"));
        list.add(new PostalInfo(	1115	,"	København K	"));
        list.add(new PostalInfo(	1116	,"	København K	"));
        list.add(new PostalInfo(	1117	,"	København K	"));
        list.add(new PostalInfo(	1118	,"	København K	"));
        list.add(new PostalInfo(	1119	,"	København K	"));
        list.add(new PostalInfo(	1120	,"	København K	"));
        list.add(new PostalInfo(	1121	,"	København K	"));
        list.add(new PostalInfo(	1122	,"	København K	"));
        list.add(new PostalInfo(	1123	,"	København K	"));
        list.add(new PostalInfo(	1124	,"	København K	"));
        list.add(new PostalInfo(	1125	,"	København K	"));
        list.add(new PostalInfo(	1126	,"	København K	"));
        list.add(new PostalInfo(	1127	,"	København K	"));
        list.add(new PostalInfo(	1128	,"	København K	"));
        list.add(new PostalInfo(	1129	,"	København K	"));
        list.add(new PostalInfo(	1130	,"	København K	"));
        list.add(new PostalInfo(	1131	,"	København K	"));
        list.add(new PostalInfo(	1140	,"	København K	"));
        list.add(new PostalInfo(	1147	,"	København K	"));
        list.add(new PostalInfo(	1148	,"	København K	"));
        list.add(new PostalInfo(	1149	,"	København K	"));
        list.add(new PostalInfo(	1150	,"	København K	"));
        list.add(new PostalInfo(	1151	,"	København K	"));
        list.add(new PostalInfo(	1152	,"	København K	"));
        list.add(new PostalInfo(	1153	,"	København K	"));
        list.add(new PostalInfo(	1154	,"	København K	"));
        list.add(new PostalInfo(	1155	,"	København K	"));
        list.add(new PostalInfo(	1156	,"	København K	"));
        list.add(new PostalInfo(	1157	,"	København K	"));
        list.add(new PostalInfo(	1158	,"	København K	"));
        list.add(new PostalInfo(	1159	,"	København K	"));
        list.add(new PostalInfo(	1160	,"	København K	"));
        list.add(new PostalInfo(	1161	,"	København K	"));
        list.add(new PostalInfo(	1162	,"	København K	"));
        list.add(new PostalInfo(	1163	,"	København K	"));
        list.add(new PostalInfo(	1164	,"	København K	"));
        list.add(new PostalInfo(	1165	,"	København K	"));
        list.add(new PostalInfo(	1166	,"	København K	"));
        list.add(new PostalInfo(	1167	,"	København K	"));
        list.add(new PostalInfo(	1168	,"	København K	"));
        list.add(new PostalInfo(	1169	,"	København K	"));
        list.add(new PostalInfo(	1170	,"	København K	"));
        list.add(new PostalInfo(	1171	,"	København K	"));
        list.add(new PostalInfo(	1172	,"	København K	"));
        list.add(new PostalInfo(	1173	,"	København K	"));
        list.add(new PostalInfo(	1174	,"	København K	"));
        list.add(new PostalInfo(	1175	,"	København K	"));
        list.add(new PostalInfo(	1200	,"	København K	"));
        list.add(new PostalInfo(	1201	,"	København K	"));
        list.add(new PostalInfo(	1202	,"	København K	"));
        list.add(new PostalInfo(	1203	,"	København K	"));
        list.add(new PostalInfo(	1204	,"	København K	"));
        list.add(new PostalInfo(	1205	,"	København K	"));
        list.add(new PostalInfo(	1206	,"	København K	"));
        list.add(new PostalInfo(	1207	,"	København K	"));
        list.add(new PostalInfo(	1208	,"	København K	"));
        list.add(new PostalInfo(	1209	,"	København K	"));
        list.add(new PostalInfo(	1210	,"	København K	"));
        list.add(new PostalInfo(	1211	,"	København K	"));
        list.add(new PostalInfo(	1212	,"	København K	"));
        list.add(new PostalInfo(	1213	,"	København K	"));
        list.add(new PostalInfo(	1214	,"	København K	"));
        list.add(new PostalInfo(	1214	,"	København K	"));
        list.add(new PostalInfo(	1215	,"	København K	"));
        list.add(new PostalInfo(	1216	,"	København K	"));
        list.add(new PostalInfo(	1217	,"	København K	"));
        list.add(new PostalInfo(	1218	,"	København K	"));
        list.add(new PostalInfo(	1218	,"	København K	"));
        list.add(new PostalInfo(	1218	,"	København K	"));
        list.add(new PostalInfo(	1218	,"	København K	"));
        list.add(new PostalInfo(	1218	,"	København K	"));
        list.add(new PostalInfo(	1218	,"	København K	"));
        list.add(new PostalInfo(	1219	,"	København K	"));
        list.add(new PostalInfo(	1220	,"	København K	"));
        list.add(new PostalInfo(	1240	,"	København K	"));
        list.add(new PostalInfo(	1250	,"	København K	"));
        list.add(new PostalInfo(	1251	,"	København K	"));
        list.add(new PostalInfo(	1252	,"	København K	"));
        list.add(new PostalInfo(	1253	,"	København K	"));
        list.add(new PostalInfo(	1254	,"	København K	"));
        list.add(new PostalInfo(	1255	,"	København K	"));
        list.add(new PostalInfo(	1256	,"	København K	"));
        list.add(new PostalInfo(	1257	,"	København K	"));
        list.add(new PostalInfo(	1258	,"	København K	"));
        list.add(new PostalInfo(	1259	,"	København K	"));
        list.add(new PostalInfo(	1259	,"	København K	"));
        list.add(new PostalInfo(	1260	,"	København K	"));
        list.add(new PostalInfo(	1261	,"	København K	"));
        list.add(new PostalInfo(	1263	,"	København K	"));
        list.add(new PostalInfo(	1263	,"	København K	"));
        list.add(new PostalInfo(	1264	,"	København K	"));
        list.add(new PostalInfo(	1265	,"	København K	"));
        list.add(new PostalInfo(	1266	,"	København K	"));
        list.add(new PostalInfo(	1267	,"	København K	"));
        list.add(new PostalInfo(	1268	,"	København K	"));
        list.add(new PostalInfo(	1270	,"	København K	"));
        list.add(new PostalInfo(	1271	,"	København K	"));
        list.add(new PostalInfo(	1291	,"	København K	"));
        list.add(new PostalInfo(	1300	,"	København K	"));
        list.add(new PostalInfo(	1301	,"	København K	"));
        list.add(new PostalInfo(	1302	,"	København K	"));
        list.add(new PostalInfo(	1303	,"	København K	"));
        list.add(new PostalInfo(	1304	,"	København K	"));
        list.add(new PostalInfo(	1306	,"	København K	"));
        list.add(new PostalInfo(	1307	,"	København K	"));
        list.add(new PostalInfo(	1307	,"	København K	"));
        list.add(new PostalInfo(	1308	,"	København K	"));
        list.add(new PostalInfo(	1309	,"	København K	"));
        list.add(new PostalInfo(	1310	,"	København K	"));
        list.add(new PostalInfo(	1311	,"	København K	"));
        list.add(new PostalInfo(	1312	,"	København K	"));
        list.add(new PostalInfo(	1313	,"	København K	"));
        list.add(new PostalInfo(	1314	,"	København K	"));
        list.add(new PostalInfo(	1315	,"	København K	"));
        list.add(new PostalInfo(	1316	,"	København K	"));
        list.add(new PostalInfo(	1317	,"	København K	"));
        list.add(new PostalInfo(	1318	,"	København K	"));
        list.add(new PostalInfo(	1319	,"	København K	"));
        list.add(new PostalInfo(	1320	,"	København K	"));
        list.add(new PostalInfo(	1321	,"	København K	"));
        list.add(new PostalInfo(	1322	,"	København K	"));
        list.add(new PostalInfo(	1323	,"	København K	"));
        list.add(new PostalInfo(	1324	,"	København K	"));
        list.add(new PostalInfo(	1325	,"	København K	"));
        list.add(new PostalInfo(	1326	,"	København K	"));
        list.add(new PostalInfo(	1327	,"	København K	"));
        list.add(new PostalInfo(	1328	,"	København K	"));
        list.add(new PostalInfo(	1329	,"	København K	"));
        list.add(new PostalInfo(	1349	,"	København K	"));
        list.add(new PostalInfo(	1350	,"	København K	"));
        list.add(new PostalInfo(	1352	,"	København K	"));
        list.add(new PostalInfo(	1353	,"	København K	"));
        list.add(new PostalInfo(	1354	,"	København K	"));
        list.add(new PostalInfo(	1355	,"	København K	"));
        list.add(new PostalInfo(	1356	,"	København K	"));
        list.add(new PostalInfo(	1357	,"	København K	"));
        list.add(new PostalInfo(	1358	,"	København K	"));
        list.add(new PostalInfo(	1359	,"	København K	"));
        list.add(new PostalInfo(	1360	,"	København K	"));
        list.add(new PostalInfo(	1361	,"	København K	"));
        list.add(new PostalInfo(	1361	,"	København K	"));
        list.add(new PostalInfo(	1362	,"	København K	"));
        list.add(new PostalInfo(	1363	,"	København K	"));
        list.add(new PostalInfo(	1364	,"	København K	"));
        list.add(new PostalInfo(	1365	,"	København K	"));
        list.add(new PostalInfo(	1366	,"	København K	"));
        list.add(new PostalInfo(	1367	,"	København K	"));
        list.add(new PostalInfo(	1368	,"	København K	"));
        list.add(new PostalInfo(	1369	,"	København K	"));
        list.add(new PostalInfo(	1370	,"	København K	"));
        list.add(new PostalInfo(	1371	,"	København K	"));
        list.add(new PostalInfo(	1390	,"	København K	"));
        list.add(new PostalInfo(	1399	,"	København K	"));
        list.add(new PostalInfo(	1400	,"	København K	"));
        list.add(new PostalInfo(	1400	,"	København K	"));
        list.add(new PostalInfo(	1401	,"	København K	"));
        list.add(new PostalInfo(	1402	,"	København K	"));
        list.add(new PostalInfo(	1402	,"	København K	"));
        list.add(new PostalInfo(	1402	,"	København K	"));
        list.add(new PostalInfo(	1402	,"	København K	"));
        list.add(new PostalInfo(	1402	,"	København K	"));
        list.add(new PostalInfo(	1403	,"	København K	"));
        list.add(new PostalInfo(	1404	,"	København K	"));
        list.add(new PostalInfo(	1405	,"	København K	"));
        list.add(new PostalInfo(	1406	,"	København K	"));
        list.add(new PostalInfo(	1407	,"	København K	"));
        list.add(new PostalInfo(	1408	,"	København K	"));
        list.add(new PostalInfo(	1409	,"	København K	"));
        list.add(new PostalInfo(	1410	,"	København K	"));
        list.add(new PostalInfo(	1411	,"	København K	"));
        list.add(new PostalInfo(	1411	,"	København K	"));
        list.add(new PostalInfo(	1412	,"	København K	"));
        list.add(new PostalInfo(	1413	,"	København K	"));
        list.add(new PostalInfo(	1414	,"	København K	"));
        list.add(new PostalInfo(	1415	,"	København K	"));
        list.add(new PostalInfo(	1416	,"	København K	"));
        list.add(new PostalInfo(	1417	,"	København K	"));
        list.add(new PostalInfo(	1418	,"	København K	"));
        list.add(new PostalInfo(	1419	,"	København K	"));
        list.add(new PostalInfo(	1420	,"	København K	"));
        list.add(new PostalInfo(	1421	,"	København K	"));
        list.add(new PostalInfo(	1422	,"	København K	"));
        list.add(new PostalInfo(	1423	,"	København K	"));
        list.add(new PostalInfo(	1424	,"	København K	"));
        list.add(new PostalInfo(	1425	,"	København K	"));
        list.add(new PostalInfo(	1426	,"	København K	"));
        list.add(new PostalInfo(	1427	,"	København K	"));
        list.add(new PostalInfo(	1428	,"	København K	"));
        list.add(new PostalInfo(	1429	,"	København K	"));
        list.add(new PostalInfo(	1430	,"	København K	"));
        list.add(new PostalInfo(	1431	,"	København K	"));
        list.add(new PostalInfo(	1432	,"	København K	"));
        list.add(new PostalInfo(	1432	,"	København K	"));
        list.add(new PostalInfo(	1432	,"	København K	"));
        list.add(new PostalInfo(	1433	,"	København K	"));
        list.add(new PostalInfo(	1433	,"	København K	"));
        list.add(new PostalInfo(	1433	,"	København K	"));
        list.add(new PostalInfo(	1433	,"	København K	"));
        list.add(new PostalInfo(	1433	,"	København K	"));
        list.add(new PostalInfo(	1433	,"	København K	"));
        list.add(new PostalInfo(	1433	,"	København K	"));
        list.add(new PostalInfo(	1434	,"	København K	"));
        list.add(new PostalInfo(	1435	,"	København K	"));
        list.add(new PostalInfo(	1436	,"	København K	"));
        list.add(new PostalInfo(	1436	,"	København K	"));
        list.add(new PostalInfo(	1436	,"	København K	"));
        list.add(new PostalInfo(	1436	,"	København K	"));
        list.add(new PostalInfo(	1436	,"	København K	"));
        list.add(new PostalInfo(	1436	,"	København K	"));
        list.add(new PostalInfo(	1436	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1437	,"	København K	"));
        list.add(new PostalInfo(	1438	,"	København K	"));
        list.add(new PostalInfo(	1438	,"	København K	"));
        list.add(new PostalInfo(	1438	,"	København K	"));
        list.add(new PostalInfo(	1438	,"	København K	"));
        list.add(new PostalInfo(	1438	,"	København K	"));
        list.add(new PostalInfo(	1438	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1439	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1440	,"	København K	"));
        list.add(new PostalInfo(	1441	,"	København K	"));
        list.add(new PostalInfo(	1441	,"	København K	"));
        list.add(new PostalInfo(	1441	,"	København K	"));
        list.add(new PostalInfo(	1448	,"	København K	"));
        list.add(new PostalInfo(	1450	,"	København K	"));
        list.add(new PostalInfo(	1451	,"	København K	"));
        list.add(new PostalInfo(	1452	,"	København K	"));
        list.add(new PostalInfo(	1453	,"	København K	"));
        list.add(new PostalInfo(	1454	,"	København K	"));
        list.add(new PostalInfo(	1455	,"	København K	"));
        list.add(new PostalInfo(	1456	,"	København K	"));
        list.add(new PostalInfo(	1457	,"	København K	"));
        list.add(new PostalInfo(	1458	,"	København K	"));
        list.add(new PostalInfo(	1459	,"	København K	"));
        list.add(new PostalInfo(	1460	,"	København K	"));
        list.add(new PostalInfo(	1461	,"	København K	"));
        list.add(new PostalInfo(	1462	,"	København K	"));
        list.add(new PostalInfo(	1463	,"	København K	"));
        list.add(new PostalInfo(	1464	,"	København K	"));
        list.add(new PostalInfo(	1465	,"	København K	"));
        list.add(new PostalInfo(	1466	,"	København K	"));
        list.add(new PostalInfo(	1467	,"	København K	"));
        list.add(new PostalInfo(	1468	,"	København K	"));
        list.add(new PostalInfo(	1470	,"	København K	"));
        list.add(new PostalInfo(	1471	,"	København K	"));
        list.add(new PostalInfo(	1472	,"	København K	"));
        list.add(new PostalInfo(	1473	,"	København K	"));
        list.add(new PostalInfo(	1500	,"	København V	"));
        list.add(new PostalInfo(	1501	,"	København V	"));
        list.add(new PostalInfo(	1502	,"	København V	"));
        list.add(new PostalInfo(	1503	,"	København V	"));
        list.add(new PostalInfo(	1504	,"	København V	"));
        list.add(new PostalInfo(	1505	,"	København V	"));
        list.add(new PostalInfo(	1506	,"	København V	"));
        list.add(new PostalInfo(	1507	,"	København V	"));
        list.add(new PostalInfo(	1508	,"	København V	"));
        list.add(new PostalInfo(	1509	,"	København V	"));
        list.add(new PostalInfo(	1510	,"	København V	"));
        list.add(new PostalInfo(	1532	,"	København V	"));
        list.add(new PostalInfo(	1533	,"	København V	"));
        list.add(new PostalInfo(	1550	,"	København V	"));
        list.add(new PostalInfo(	1550	,"	København V	"));
        list.add(new PostalInfo(	1551	,"	København V	"));
        list.add(new PostalInfo(	1552	,"	København V	"));
        list.add(new PostalInfo(	1553	,"	København V	"));
        list.add(new PostalInfo(	1553	,"	København V	"));
        list.add(new PostalInfo(	1554	,"	København V	"));
        list.add(new PostalInfo(	1555	,"	København V	"));
        list.add(new PostalInfo(	1556	,"	København V	"));
        list.add(new PostalInfo(	1557	,"	København V	"));
        list.add(new PostalInfo(	1558	,"	København V	"));
        list.add(new PostalInfo(	1559	,"	København V	"));
        list.add(new PostalInfo(	1560	,"	København V	"));
        list.add(new PostalInfo(	1561	,"	København V	"));
        list.add(new PostalInfo(	1561	,"	København V	"));
        list.add(new PostalInfo(	1562	,"	København V	"));
        list.add(new PostalInfo(	1563	,"	København V	"));
        list.add(new PostalInfo(	1564	,"	København V	"));
        list.add(new PostalInfo(	1566	,"	København V	"));
        list.add(new PostalInfo(	1567	,"	København V	"));
        list.add(new PostalInfo(	1568	,"	København V	"));
        list.add(new PostalInfo(	1569	,"	København V	"));
        list.add(new PostalInfo(	1570	,"	København V	"));
        list.add(new PostalInfo(	1570	,"	København V	"));
        list.add(new PostalInfo(	1571	,"	København V	"));
        list.add(new PostalInfo(	1572	,"	København V	"));
        list.add(new PostalInfo(	1573	,"	København V	"));
        list.add(new PostalInfo(	1574	,"	København V	"));
        list.add(new PostalInfo(	1575	,"	København V	"));
        list.add(new PostalInfo(	1576	,"	København V	"));
        list.add(new PostalInfo(	1577	,"	København V	"));
        list.add(new PostalInfo(	1590	,"	København V	"));
        list.add(new PostalInfo(	1592	,"	København V	"));
        list.add(new PostalInfo(	1595	,"	København V	"));
        list.add(new PostalInfo(	1599	,"	København V	"));
        list.add(new PostalInfo(	1600	,"	København V	"));
        list.add(new PostalInfo(	1601	,"	København V	"));
        list.add(new PostalInfo(	1602	,"	København V	"));
        list.add(new PostalInfo(	1603	,"	København V	"));
        list.add(new PostalInfo(	1604	,"	København V	"));
        list.add(new PostalInfo(	1605	,"	København V	"));
        list.add(new PostalInfo(	1606	,"	København V	"));
        list.add(new PostalInfo(	1607	,"	København V	"));
        list.add(new PostalInfo(	1608	,"	København V	"));
        list.add(new PostalInfo(	1609	,"	København V	"));
        list.add(new PostalInfo(	1610	,"	København V	"));
        list.add(new PostalInfo(	1611	,"	København V	"));
        list.add(new PostalInfo(	1612	,"	København V	"));
        list.add(new PostalInfo(	1613	,"	København V	"));
        list.add(new PostalInfo(	1614	,"	København V	"));
        list.add(new PostalInfo(	1615	,"	København V	"));
        list.add(new PostalInfo(	1616	,"	København V	"));
        list.add(new PostalInfo(	1617	,"	København V	"));
        list.add(new PostalInfo(	1618	,"	København V	"));
        list.add(new PostalInfo(	1619	,"	København V	"));
        list.add(new PostalInfo(	1620	,"	København V	"));
        list.add(new PostalInfo(	1620	,"	København V	"));
        list.add(new PostalInfo(	1621	,"	København V	"));
        list.add(new PostalInfo(	1622	,"	København V	"));
        list.add(new PostalInfo(	1623	,"	København V	"));
        list.add(new PostalInfo(	1624	,"	København V	"));
        list.add(new PostalInfo(	1630	,"	København V	"));
        list.add(new PostalInfo(	1631	,"	København V	"));
        list.add(new PostalInfo(	1632	,"	København V	"));
        list.add(new PostalInfo(	1633	,"	København V	"));
        list.add(new PostalInfo(	1634	,"	København V	"));
        list.add(new PostalInfo(	1635	,"	København V	"));
        list.add(new PostalInfo(	1639	,"	København V	"));
        list.add(new PostalInfo(	1640	,"	København V	"));
        list.add(new PostalInfo(	1650	,"	København V	"));
        list.add(new PostalInfo(	1651	,"	København V	"));
        list.add(new PostalInfo(	1652	,"	København V	"));
        list.add(new PostalInfo(	1653	,"	København V	"));
        list.add(new PostalInfo(	1654	,"	København V	"));
        list.add(new PostalInfo(	1655	,"	København V	"));
        list.add(new PostalInfo(	1656	,"	København V	"));
        list.add(new PostalInfo(	1657	,"	København V	"));
        list.add(new PostalInfo(	1658	,"	København V	"));
        list.add(new PostalInfo(	1659	,"	København V	"));
        list.add(new PostalInfo(	1660	,"	København V	"));
        list.add(new PostalInfo(	1660	,"	København V	"));
        list.add(new PostalInfo(	1661	,"	København V	"));
        list.add(new PostalInfo(	1662	,"	København V	"));
        list.add(new PostalInfo(	1663	,"	København V	"));
        list.add(new PostalInfo(	1664	,"	København V	"));
        list.add(new PostalInfo(	1665	,"	København V	"));
        list.add(new PostalInfo(	1666	,"	København V	"));
        list.add(new PostalInfo(	1667	,"	København V	"));
        list.add(new PostalInfo(	1668	,"	København V	"));
        list.add(new PostalInfo(	1669	,"	København V	"));
        list.add(new PostalInfo(	1670	,"	København V	"));
        list.add(new PostalInfo(	1671	,"	København V	"));
        list.add(new PostalInfo(	1671	,"	København V	"));
        list.add(new PostalInfo(	1672	,"	København V	"));
        list.add(new PostalInfo(	1673	,"	København V	"));
        list.add(new PostalInfo(	1674	,"	København V	"));
        list.add(new PostalInfo(	1675	,"	København V	"));
        list.add(new PostalInfo(	1676	,"	København V	"));
        list.add(new PostalInfo(	1677	,"	København V	"));
        list.add(new PostalInfo(	1699	,"	København V	"));
        list.add(new PostalInfo(	1700	,"	København V	"));
        list.add(new PostalInfo(	1701	,"	København V	"));
        list.add(new PostalInfo(	1702	,"	København V	"));
        list.add(new PostalInfo(	1703	,"	København V	"));
        list.add(new PostalInfo(	1704	,"	København V	"));
        list.add(new PostalInfo(	1705	,"	København V	"));
        list.add(new PostalInfo(	1706	,"	København V	"));
        list.add(new PostalInfo(	1707	,"	København V	"));
        list.add(new PostalInfo(	1708	,"	København V	"));
        list.add(new PostalInfo(	1709	,"	København V	"));
        list.add(new PostalInfo(	1710	,"	København V	"));
        list.add(new PostalInfo(	1711	,"	København V	"));
        list.add(new PostalInfo(	1712	,"	København V	"));
        list.add(new PostalInfo(	1713	,"	København V	"));
        list.add(new PostalInfo(	1714	,"	København V	"));
        list.add(new PostalInfo(	1715	,"	København V	"));
        list.add(new PostalInfo(	1716	,"	København V	"));
        list.add(new PostalInfo(	1717	,"	København V	"));
        list.add(new PostalInfo(	1718	,"	København V	"));
        list.add(new PostalInfo(	1719	,"	København V	"));
        list.add(new PostalInfo(	1720	,"	København V	"));
        list.add(new PostalInfo(	1721	,"	København V	"));
        list.add(new PostalInfo(	1722	,"	København V	"));
        list.add(new PostalInfo(	1723	,"	København V	"));
        list.add(new PostalInfo(	1724	,"	København V	"));
        list.add(new PostalInfo(	1725	,"	København V	"));
        list.add(new PostalInfo(	1726	,"	København V	"));
        list.add(new PostalInfo(	1727	,"	København V	"));
        list.add(new PostalInfo(	1728	,"	København V	"));
        list.add(new PostalInfo(	1729	,"	København V	"));
        list.add(new PostalInfo(	1730	,"	København V	"));
        list.add(new PostalInfo(	1731	,"	København V	"));
        list.add(new PostalInfo(	1732	,"	København V	"));
        list.add(new PostalInfo(	1733	,"	København V	"));
        list.add(new PostalInfo(	1734	,"	København V	"));
        list.add(new PostalInfo(	1735	,"	København V	"));
        list.add(new PostalInfo(	1736	,"	København V	"));
        list.add(new PostalInfo(	1737	,"	København V	"));
        list.add(new PostalInfo(	1738	,"	København V	"));
        list.add(new PostalInfo(	1739	,"	København V	"));
        list.add(new PostalInfo(	1748	,"	København V	"));
        list.add(new PostalInfo(	1749	,"	København V	"));
        list.add(new PostalInfo(	1750	,"	København V	"));
        list.add(new PostalInfo(	1751	,"	København V	"));
        list.add(new PostalInfo(	1752	,"	København V	"));
        list.add(new PostalInfo(	1753	,"	København V	"));
        list.add(new PostalInfo(	1754	,"	København V	"));
        list.add(new PostalInfo(	1755	,"	København V	"));
        list.add(new PostalInfo(	1756	,"	København V	"));
        list.add(new PostalInfo(	1757	,"	København V	"));
        list.add(new PostalInfo(	1758	,"	København V	"));
        list.add(new PostalInfo(	1759	,"	København V	"));
        list.add(new PostalInfo(	1760	,"	København V	"));
        list.add(new PostalInfo(	1761	,"	København V	"));
        list.add(new PostalInfo(	1762	,"	København V	"));
        list.add(new PostalInfo(	1763	,"	København V	"));
        list.add(new PostalInfo(	1764	,"	København V	"));
        list.add(new PostalInfo(	1765	,"	København V	"));
        list.add(new PostalInfo(	1766	,"	København V	"));
        list.add(new PostalInfo(	1770	,"	København V	"));
        list.add(new PostalInfo(	1771	,"	København V	"));
        list.add(new PostalInfo(	1772	,"	København V	"));
        list.add(new PostalInfo(	1773	,"	København V	"));
        list.add(new PostalInfo(	1774	,"	København V	"));
        list.add(new PostalInfo(	1775	,"	København V	"));
        list.add(new PostalInfo(	1777	,"	København V	"));
        list.add(new PostalInfo(	1778	,"	København V	"));
        list.add(new PostalInfo(	1780	,"	København V	"));
        list.add(new PostalInfo(	1782	,"	København V	"));
        list.add(new PostalInfo(	1783	,"	København V	"));
        list.add(new PostalInfo(	1784	,"	København V	"));
        list.add(new PostalInfo(	1785	,"	København V	"));
        list.add(new PostalInfo(	1786	,"	København V	"));
        list.add(new PostalInfo(	1787	,"	København V	"));
        list.add(new PostalInfo(	1788	,"	København V	"));
        list.add(new PostalInfo(	1789	,"	København V	"));
        list.add(new PostalInfo(	1790	,"	København V	"));
        list.add(new PostalInfo(	1795	,"	København V	"));
        list.add(new PostalInfo(	1799	,"	København V	"));
        list.add(new PostalInfo(	1800	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1801	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1802	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1803	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1804	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1805	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1806	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1807	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1808	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1809	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1810	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1811	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1812	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1813	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1814	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1815	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1816	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1817	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1818	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1819	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1820	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1822	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1823	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1824	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1825	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1826	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1827	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1828	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1829	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1835	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1850	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1851	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1852	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1853	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1854	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1855	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1856	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1857	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1860	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1861	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1862	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1863	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1864	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1865	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1866	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1867	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1868	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1870	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1871	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1872	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1873	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1874	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1875	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1876	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1877	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1878	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1879	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1900	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1901	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1902	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1903	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1904	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1905	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1906	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1908	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1909	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1910	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1911	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1912	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1913	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1914	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1915	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1916	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1917	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1920	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1921	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1922	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1923	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1924	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1925	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1926	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1927	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1928	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1931	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1950	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1951	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1952	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1953	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1954	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1955	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1956	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1957	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1958	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1959	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1960	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1961	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1962	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1963	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1964	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1965	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1966	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1967	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1970	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1971	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1972	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1973	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1974	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	1999	,"	Frederiksberg C	"));
        list.add(new PostalInfo(	2000	,"	Frederiksberg	"));
        list.add(new PostalInfo(	2100	,"	København Ø	"));
        list.add(new PostalInfo(	2200	,"	København N	"));
        list.add(new PostalInfo(	2300	,"	København S	"));
        list.add(new PostalInfo(	2400	,"	København NV	"));
        list.add(new PostalInfo(	2450	,"	København SV	"));
        list.add(new PostalInfo(	2500	,"	Valby	"));
        list.add(new PostalInfo(	2600	,"	Glostrup	"));
        list.add(new PostalInfo(	2605	,"	Brøndby	"));
        list.add(new PostalInfo(	2610	,"	Rødovre	"));
        list.add(new PostalInfo(	2620	,"	Albertslund	"));
        list.add(new PostalInfo(	2625	,"	Vallensbæk	"));
        list.add(new PostalInfo(	2630	,"	Taastrup	"));
        list.add(new PostalInfo(	2633	,"	Taastrup	"));
        list.add(new PostalInfo(	2635	,"	Ishøj	"));
        list.add(new PostalInfo(	2640	,"	Hedehusene	"));
        list.add(new PostalInfo(	2650	,"	Hvidovre	"));
        list.add(new PostalInfo(	2660	,"	Brøndby Strand	"));
        list.add(new PostalInfo(	2665	,"	Vallensbæk Strand	"));
        list.add(new PostalInfo(	2670	,"	Greve	"));
        list.add(new PostalInfo(	2680	,"	Solrød Strand	"));
        list.add(new PostalInfo(	2690	,"	Karlslunde	"));
        list.add(new PostalInfo(	2700	,"	Brønshøj	"));
        list.add(new PostalInfo(	2720	,"	Vanløse	"));
        list.add(new PostalInfo(	2730	,"	Herlev	"));
        list.add(new PostalInfo(	2740	,"	Skovlunde	"));
        list.add(new PostalInfo(	2750	,"	Ballerup	"));
        list.add(new PostalInfo(	2760	,"	Måløv	"));
        list.add(new PostalInfo(	2765	,"	Smørum	"));
        list.add(new PostalInfo(	2770	,"	Kastrup	"));
        list.add(new PostalInfo(	2791	,"	Dragør	"));
        list.add(new PostalInfo(	2800	,"	Kongens Lyngby	"));
        list.add(new PostalInfo(	2820	,"	Gentofte	"));
        list.add(new PostalInfo(	2830	,"	Virum	"));
        list.add(new PostalInfo(	2840	,"	Holte	"));
        list.add(new PostalInfo(	2850	,"	Nærum	"));
        list.add(new PostalInfo(	2860	,"	Søborg	"));
        list.add(new PostalInfo(	2870	,"	Dyssegård	"));
        list.add(new PostalInfo(	2880	,"	Bagsværd	"));
        list.add(new PostalInfo(	2900	,"	Hellerup	"));
        list.add(new PostalInfo(	2920	,"	Charlottenlund	"));
        list.add(new PostalInfo(	2930	,"	Klampenborg	"));
        list.add(new PostalInfo(	2942	,"	Skodsborg	"));
        list.add(new PostalInfo(	2950	,"	Vedbæk	"));
        list.add(new PostalInfo(	2960	,"	Rungsted Kyst	"));
        list.add(new PostalInfo(	2970	,"	Hørsholm	"));
        list.add(new PostalInfo(	2980	,"	Kokkedal	"));
        list.add(new PostalInfo(	2990	,"	Nivå	"));
        list.add(new PostalInfo(	3000	,"	Helsingør	"));
        list.add(new PostalInfo(	3050	,"	Humlebæk	"));
        list.add(new PostalInfo(	3060	,"	Espergærde	"));
        list.add(new PostalInfo(	3070	,"	Snekkersten	"));
        list.add(new PostalInfo(	3080	,"	Tikøb	"));
        list.add(new PostalInfo(	3100	,"	Hornbæk	"));
        list.add(new PostalInfo(	3120	,"	Dronningmølle	"));
        list.add(new PostalInfo(	3140	,"	Ålsgårde	"));
        list.add(new PostalInfo(	3150	,"	Hellebæk	"));
        list.add(new PostalInfo(	3200	,"	Helsinge	"));
        list.add(new PostalInfo(	3210	,"	Vejby	"));
        list.add(new PostalInfo(	3220	,"	Tisvildeleje	"));
        list.add(new PostalInfo(	3230	,"	Græsted	"));
        list.add(new PostalInfo(	3250	,"	Gilleleje	"));
        list.add(new PostalInfo(	3300	,"	Frederiksværk	"));
        list.add(new PostalInfo(	3310	,"	Ølsted	"));
        list.add(new PostalInfo(	3320	,"	Skævinge	"));
        list.add(new PostalInfo(	3330	,"	Gørløse	"));
        list.add(new PostalInfo(	3360	,"	Liseleje	"));
        list.add(new PostalInfo(	3370	,"	Melby	"));
        list.add(new PostalInfo(	3390	,"	Hundested	"));
        list.add(new PostalInfo(	3400	,"	Hillerød	"));
        list.add(new PostalInfo(	3450	,"	Allerød	"));
        list.add(new PostalInfo(	3460	,"	Birkerød	"));
        list.add(new PostalInfo(	3480	,"	Fredensborg	"));
        list.add(new PostalInfo(	3490	,"	Kvistgård	"));
        list.add(new PostalInfo(	3500	,"	Værløse	"));
        list.add(new PostalInfo(	3520	,"	Farum	"));
        list.add(new PostalInfo(	3540	,"	Lynge	"));
        list.add(new PostalInfo(	3550	,"	Slangerup	"));
        list.add(new PostalInfo(	3600	,"	Frederikssund	"));
        list.add(new PostalInfo(	3630	,"	Jægerspris	"));
        list.add(new PostalInfo(	3650	,"	Ølstykke	"));
        list.add(new PostalInfo(	3660	,"	Stenløse	"));
        list.add(new PostalInfo(	3670	,"	Veksø Sjælland	"));
        list.add(new PostalInfo(	3700	,"	Rønne	"));
        list.add(new PostalInfo(	3720	,"	Aakirkeby	"));
        list.add(new PostalInfo(	3730	,"	Nexø	"));
        list.add(new PostalInfo(	3740	,"	Svaneke	"));
        list.add(new PostalInfo(	3751	,"	Østermarie	"));
        list.add(new PostalInfo(	3760	,"	Gudhjem	"));
        list.add(new PostalInfo(	3770	,"	Allinge	"));
        list.add(new PostalInfo(	3782	,"	Klemensker	"));
        list.add(new PostalInfo(	3790	,"	Hasle	"));
        list.add(new PostalInfo(	4000	,"	Roskilde	"));
        list.add(new PostalInfo(	4040	,"	Jyllinge	"));
        list.add(new PostalInfo(	4050	,"	Skibby	"));
        list.add(new PostalInfo(	4060	,"	Kirke Såby	"));
        list.add(new PostalInfo(	4070	,"	Kirke Hyllinge	"));
        list.add(new PostalInfo(	4100	,"	Ringsted	"));
        list.add(new PostalInfo(	4105	,"	Ringsted	"));
        list.add(new PostalInfo(	4129	,"	Ringsted	"));
        list.add(new PostalInfo(	4130	,"	Viby Sjælland	"));
        list.add(new PostalInfo(	4140	,"	Borup	"));
        list.add(new PostalInfo(	4160	,"	Herlufmagle	"));
        list.add(new PostalInfo(	4171	,"	Glumsø	"));
        list.add(new PostalInfo(	4173	,"	Fjenneslev	"));
        list.add(new PostalInfo(	4174	,"	Jystrup Midtsj	"));
        list.add(new PostalInfo(	4180	,"	Sorø	"));
        list.add(new PostalInfo(	4190	,"	Munke Bjergby	"));
        list.add(new PostalInfo(	4200	,"	Slagelse	"));
        list.add(new PostalInfo(	4220	,"	Korsør	"));
        list.add(new PostalInfo(	4230	,"	Skælskør	"));
        list.add(new PostalInfo(	4241	,"	Vemmelev	"));
        list.add(new PostalInfo(	4242	,"	Boeslunde	"));
        list.add(new PostalInfo(	4243	,"	Rude	"));
        list.add(new PostalInfo(	4250	,"	Fuglebjerg	"));
        list.add(new PostalInfo(	4261	,"	Dalmose	"));
        list.add(new PostalInfo(	4262	,"	Sandved	"));
        list.add(new PostalInfo(	4270	,"	Høng	"));
        list.add(new PostalInfo(	4281	,"	Gørlev	"));
        list.add(new PostalInfo(	4291	,"	Ruds Vedby	"));
        list.add(new PostalInfo(	4293	,"	Dianalund	"));
        list.add(new PostalInfo(	4295	,"	Stenlille	"));
        list.add(new PostalInfo(	4296	,"	Nyrup	"));
        list.add(new PostalInfo(	4300	,"	Holbæk	"));
        list.add(new PostalInfo(	4320	,"	Lejre	"));
        list.add(new PostalInfo(	4330	,"	Hvalsø	"));
        list.add(new PostalInfo(	4340	,"	Tølløse	"));
        list.add(new PostalInfo(	4350	,"	Ugerløse	"));
        list.add(new PostalInfo(	4360	,"	Kirke Eskilstrup	"));
        list.add(new PostalInfo(	4370	,"	Store Merløse	"));
        list.add(new PostalInfo(	4390	,"	Vipperød	"));
        list.add(new PostalInfo(	4400	,"	Kalundborg	"));
        list.add(new PostalInfo(	4420	,"	Regstrup	"));
        list.add(new PostalInfo(	4440	,"	Mørkøv	"));
        list.add(new PostalInfo(	4450	,"	Jyderup	"));
        list.add(new PostalInfo(	4460	,"	Snertinge	"));
        list.add(new PostalInfo(	4470	,"	Svebølle	"));
        list.add(new PostalInfo(	4480	,"	Store Fuglede	"));
        list.add(new PostalInfo(	4490	,"	Jerslev Sjælland	"));
        list.add(new PostalInfo(	4500	,"	Nykøbing Sj	"));
        list.add(new PostalInfo(	4520	,"	Svinninge	"));
        list.add(new PostalInfo(	4532	,"	Gislinge	"));
        list.add(new PostalInfo(	4534	,"	Hørve	"));
        list.add(new PostalInfo(	4540	,"	Fårevejle	"));
        list.add(new PostalInfo(	4550	,"	Asnæs	"));
        list.add(new PostalInfo(	4560	,"	Vig	"));
        list.add(new PostalInfo(	4571	,"	Grevinge	"));
        list.add(new PostalInfo(	4572	,"	Nørre Asmindrup	"));
        list.add(new PostalInfo(	4573	,"	Højby	"));
        list.add(new PostalInfo(	4581	,"	Rørvig	"));
        list.add(new PostalInfo(	4583	,"	Sjællands Odde	"));
        list.add(new PostalInfo(	4591	,"	Føllenslev	"));
        list.add(new PostalInfo(	4592	,"	Sejerø	"));
        list.add(new PostalInfo(	4593	,"	Eskebjerg	"));
        list.add(new PostalInfo(	4600	,"	Køge	"));
        list.add(new PostalInfo(	4621	,"	Gadstrup	"));
        list.add(new PostalInfo(	4622	,"	Havdrup	"));
        list.add(new PostalInfo(	4623	,"	Lille Skensved	"));
        list.add(new PostalInfo(	4632	,"	Bjæverskov	"));
        list.add(new PostalInfo(	4640	,"	Fakse	"));
        list.add(new PostalInfo(	4652	,"	Hårlev	"));
        list.add(new PostalInfo(	4653	,"	Karise	"));
        list.add(new PostalInfo(	4654	,"	Fakse Ladeplads	"));
        list.add(new PostalInfo(	4660	,"	Store Heddinge	"));
        list.add(new PostalInfo(	4671	,"	Strøby	"));
        list.add(new PostalInfo(	4672	,"	Klippinge	"));
        list.add(new PostalInfo(	4673	,"	Rødvig Stevns	"));
        list.add(new PostalInfo(	4681	,"	Herfølge	"));
        list.add(new PostalInfo(	4682	,"	Tureby	"));
        list.add(new PostalInfo(	4683	,"	Rønnede	"));
        list.add(new PostalInfo(	4684	,"	Holmegaard	"));
        list.add(new PostalInfo(	4690	,"	Haslev	"));
        list.add(new PostalInfo(	4700	,"	Næstved	"));
        list.add(new PostalInfo(	4720	,"	Præstø	"));
        list.add(new PostalInfo(	4733	,"	Tappernøje	"));
        list.add(new PostalInfo(	4735	,"	Mern	"));
        list.add(new PostalInfo(	4736	,"	Karrebæksminde	"));
        list.add(new PostalInfo(	4750	,"	Lundby	"));
        list.add(new PostalInfo(	4760	,"	Vordingborg	"));
        list.add(new PostalInfo(	4771	,"	Kalvehave	"));
        list.add(new PostalInfo(	4772	,"	Langebæk	"));
        list.add(new PostalInfo(	4773	,"	Stensved	"));
        list.add(new PostalInfo(	4780	,"	Stege	"));
        list.add(new PostalInfo(	4791	,"	Borre	"));
        list.add(new PostalInfo(	4792	,"	Askeby	"));
        list.add(new PostalInfo(	4793	,"	Bogø By	"));
        list.add(new PostalInfo(	4800	,"	Nykøbing F	"));
        list.add(new PostalInfo(	4840	,"	Nørre Alslev	"));
        list.add(new PostalInfo(	4850	,"	Stubbekøbing	"));
        list.add(new PostalInfo(	4862	,"	Guldborg	"));
        list.add(new PostalInfo(	4863	,"	Eskilstrup	"));
        list.add(new PostalInfo(	4871	,"	Horbelev	"));
        list.add(new PostalInfo(	4872	,"	Idestrup	"));
        list.add(new PostalInfo(	4873	,"	Væggerløse	"));
        list.add(new PostalInfo(	4874	,"	Gedser	"));
        list.add(new PostalInfo(	4880	,"	Nysted	"));
        list.add(new PostalInfo(	4891	,"	Toreby L	"));
        list.add(new PostalInfo(	4892	,"	Kettinge	"));
        list.add(new PostalInfo(	4894	,"	Øster Ulslev	"));
        list.add(new PostalInfo(	4895	,"	Errindlev	"));
        list.add(new PostalInfo(	4900	,"	Nakskov	"));
        list.add(new PostalInfo(	4912	,"	Harpelunde	"));
        list.add(new PostalInfo(	4913	,"	Horslunde	"));
        list.add(new PostalInfo(	4920	,"	Søllested	"));
        list.add(new PostalInfo(	4930	,"	Maribo	"));
        list.add(new PostalInfo(	4941	,"	Bandholm	"));
        list.add(new PostalInfo(	4943	,"	Torrig L	"));
        list.add(new PostalInfo(	4944	,"	Fejø	"));
        list.add(new PostalInfo(	4951	,"	Nørreballe	"));
        list.add(new PostalInfo(	4952	,"	Stokkemarke	"));
        list.add(new PostalInfo(	4953	,"	Vesterborg	"));
        list.add(new PostalInfo(	4960	,"	Holeby	"));
        list.add(new PostalInfo(	4970	,"	Rødby	"));
        list.add(new PostalInfo(	4983	,"	Dannemare	"));
        list.add(new PostalInfo(	4990	,"	Sakskøbing	"));
        list.add(new PostalInfo(	5000	,"	Odense C	"));
        list.add(new PostalInfo(	5029	,"	Odense C	"));
        list.add(new PostalInfo(	5090	,"	Odense C	"));
        list.add(new PostalInfo(	5100	,"	Odense C	"));
        list.add(new PostalInfo(	5200	,"	Odense V	"));
        list.add(new PostalInfo(	5210	,"	Odense NV	"));
        list.add(new PostalInfo(	5220	,"	Odense SØ	"));
        list.add(new PostalInfo(	5230	,"	Odense M	"));
        list.add(new PostalInfo(	5240	,"	Odense NØ	"));
        list.add(new PostalInfo(	5250	,"	Odense SV	"));
        list.add(new PostalInfo(	5260	,"	Odense S	"));
        list.add(new PostalInfo(	5270	,"	Odense N	"));
        list.add(new PostalInfo(	5290	,"	Marslev	"));
        list.add(new PostalInfo(	5300	,"	Kerteminde	"));
        list.add(new PostalInfo(	5320	,"	Agedrup	"));
        list.add(new PostalInfo(	5330	,"	Munkebo	"));
        list.add(new PostalInfo(	5350	,"	Rynkeby	"));
        list.add(new PostalInfo(	5370	,"	Mesinge	"));
        list.add(new PostalInfo(	5380	,"	Dalby	"));
        list.add(new PostalInfo(	5390	,"	Martofte	"));
        list.add(new PostalInfo(	5400	,"	Bogense	"));
        list.add(new PostalInfo(	5450	,"	Otterup	"));
        list.add(new PostalInfo(	5462	,"	Morud	"));
        list.add(new PostalInfo(	5463	,"	Harndrup	"));
        list.add(new PostalInfo(	5464	,"	Brenderup Fyn	"));
        list.add(new PostalInfo(	5466	,"	Asperup	"));
        list.add(new PostalInfo(	5471	,"	Søndersø	"));
        list.add(new PostalInfo(	5474	,"	Veflinge	"));
        list.add(new PostalInfo(	5485	,"	Skamby	"));
        list.add(new PostalInfo(	5491	,"	Blommenslyst	"));
        list.add(new PostalInfo(	5492	,"	Vissenbjerg	"));
        list.add(new PostalInfo(	5500	,"	Middelfart	"));
        list.add(new PostalInfo(	5540	,"	Ullerslev	"));
        list.add(new PostalInfo(	5550	,"	Langeskov	"));
        list.add(new PostalInfo(	5560	,"	Aarup	"));
        list.add(new PostalInfo(	5580	,"	Nørre Aaby	"));
        list.add(new PostalInfo(	5591	,"	Gelsted	"));
        list.add(new PostalInfo(	5592	,"	Ejby	"));
        list.add(new PostalInfo(	5600	,"	Faaborg	"));
        list.add(new PostalInfo(	5610	,"	Assens	"));
        list.add(new PostalInfo(	5620	,"	Glamsbjerg	"));
        list.add(new PostalInfo(	5631	,"	Ebberup	"));
        list.add(new PostalInfo(	5642	,"	Millinge	"));
        list.add(new PostalInfo(	5672	,"	Broby	"));
        list.add(new PostalInfo(	5683	,"	Haarby	"));
        list.add(new PostalInfo(	5690	,"	Tommerup	"));
        list.add(new PostalInfo(	5700	,"	Svendborg	"));
        list.add(new PostalInfo(	5750	,"	Ringe	"));
        list.add(new PostalInfo(	5762	,"	Vester Skerninge	"));
        list.add(new PostalInfo(	5771	,"	Stenstrup	"));
        list.add(new PostalInfo(	5772	,"	Kværndrup	"));
        list.add(new PostalInfo(	5792	,"	Årslev	"));
        list.add(new PostalInfo(	5800	,"	Nyborg	"));
        list.add(new PostalInfo(	5853	,"	Ørbæk	"));
        list.add(new PostalInfo(	5854	,"	Gislev	"));
        list.add(new PostalInfo(	5856	,"	Ryslinge	"));
        list.add(new PostalInfo(	5863	,"	Ferritslev Fyn	"));
        list.add(new PostalInfo(	5871	,"	Frørup	"));
        list.add(new PostalInfo(	5874	,"	Hesselager	"));
        list.add(new PostalInfo(	5881	,"	Skårup Fyn	"));
        list.add(new PostalInfo(	5882	,"	Vejstrup	"));
        list.add(new PostalInfo(	5883	,"	Oure	"));
        list.add(new PostalInfo(	5884	,"	Gudme	"));
        list.add(new PostalInfo(	5892	,"	Gudbjerg Sydfyn	"));
        list.add(new PostalInfo(	5900	,"	Rudkøbing	"));
        list.add(new PostalInfo(	5932	,"	Humble	"));
        list.add(new PostalInfo(	5935	,"	Bagenkop	"));
        list.add(new PostalInfo(	5953	,"	Tranekær	"));
        list.add(new PostalInfo(	5960	,"	Marstal	"));
        list.add(new PostalInfo(	5970	,"	Ærøskøbing	"));
        list.add(new PostalInfo(	5985	,"	Søby Ærø	"));
        list.add(new PostalInfo(	6000	,"	Kolding	"));
        list.add(new PostalInfo(	6040	,"	Egtved	"));
        list.add(new PostalInfo(	6051	,"	Almind	"));
        list.add(new PostalInfo(	6052	,"	Viuf	"));
        list.add(new PostalInfo(	6064	,"	Jordrup	"));
        list.add(new PostalInfo(	6070	,"	Christiansfeld	"));
        list.add(new PostalInfo(	6091	,"	Bjert	"));
        list.add(new PostalInfo(	6092	,"	Sønder Stenderup	"));
        list.add(new PostalInfo(	6093	,"	Sjølund	"));
        list.add(new PostalInfo(	6094	,"	Hejls	"));
        list.add(new PostalInfo(	6100	,"	Haderslev	"));
        list.add(new PostalInfo(	6200	,"	Aabenraa	"));
        list.add(new PostalInfo(	6230	,"	Rødekro	"));
        list.add(new PostalInfo(	6240	,"	Løgumkloster	"));
        list.add(new PostalInfo(	6261	,"	Bredebro	"));
        list.add(new PostalInfo(	6270	,"	Tønder	"));
        list.add(new PostalInfo(	6280	,"	Højer	"));
        list.add(new PostalInfo(	6300	,"	Gråsten	"));
        list.add(new PostalInfo(	6310	,"	Broager	"));
        list.add(new PostalInfo(	6320	,"	Egernsund	"));
        list.add(new PostalInfo(	6330	,"	Padborg	"));
        list.add(new PostalInfo(	6340	,"	Kruså	"));
        list.add(new PostalInfo(	6360	,"	Tinglev	"));
        list.add(new PostalInfo(	6372	,"	Bylderup-Bov	"));
        list.add(new PostalInfo(	6392	,"	Bolderslev	"));
        list.add(new PostalInfo(	6400	,"	Sønderborg	"));
        list.add(new PostalInfo(	6430	,"	Nordborg	"));
        list.add(new PostalInfo(	6440	,"	Augustenborg	"));
        list.add(new PostalInfo(	6470	,"	Sydals	"));
        list.add(new PostalInfo(	6500	,"	Vojens	"));
        list.add(new PostalInfo(	6510	,"	Gram	"));
        list.add(new PostalInfo(	6520	,"	Toftlund	"));
        list.add(new PostalInfo(	6534	,"	Agerskov	"));
        list.add(new PostalInfo(	6535	,"	Branderup J	"));
        list.add(new PostalInfo(	6541	,"	Bevtoft	"));
        list.add(new PostalInfo(	6560	,"	Sommersted	"));
        list.add(new PostalInfo(	6580	,"	Vamdrup	"));
        list.add(new PostalInfo(	6600	,"	Vejen	"));
        list.add(new PostalInfo(	6621	,"	Gesten	"));
        list.add(new PostalInfo(	6622	,"	Bække	"));
        list.add(new PostalInfo(	6623	,"	Vorbasse	"));
        list.add(new PostalInfo(	6630	,"	Rødding	"));
        list.add(new PostalInfo(	6640	,"	Lunderskov	"));
        list.add(new PostalInfo(	6650	,"	Brørup	"));
        list.add(new PostalInfo(	6660	,"	Lintrup	"));
        list.add(new PostalInfo(	6670	,"	Holsted	"));
        list.add(new PostalInfo(	6682	,"	Hovborg	"));
        list.add(new PostalInfo(	6683	,"	Føvling	"));
        list.add(new PostalInfo(	6690	,"	Gørding	"));
        list.add(new PostalInfo(	6700	,"	Esbjerg	"));
        list.add(new PostalInfo(	6701	,"	Esbjerg	"));
        list.add(new PostalInfo(	6705	,"	Esbjerg Ø	"));
        list.add(new PostalInfo(	6710	,"	Esbjerg V	"));
        list.add(new PostalInfo(	6715	,"	Esbjerg N	"));
        list.add(new PostalInfo(	6720	,"	Fanø	"));
        list.add(new PostalInfo(	6731	,"	Tjæreborg	"));
        list.add(new PostalInfo(	6740	,"	Bramming	"));
        list.add(new PostalInfo(	6752	,"	Glejbjerg	"));
        list.add(new PostalInfo(	6753	,"	Agerbæk	"));
        list.add(new PostalInfo(	6760	,"	Ribe	"));
        list.add(new PostalInfo(	6771	,"	Gredstedbro	"));
        list.add(new PostalInfo(	6780	,"	Skærbæk	"));
        list.add(new PostalInfo(	6792	,"	Rømø	"));
        list.add(new PostalInfo(	6800	,"	Varde	"));
        list.add(new PostalInfo(	6818	,"	Årre	"));
        list.add(new PostalInfo(	6823	,"	Ansager	"));
        list.add(new PostalInfo(	6830	,"	Nørre Nebel	"));
        list.add(new PostalInfo(	6840	,"	Oksbøl	"));
        list.add(new PostalInfo(	6851	,"	Janderup Vestj	"));
        list.add(new PostalInfo(	6852	,"	Billum	"));
        list.add(new PostalInfo(	6853	,"	Vejers Strand	"));
        list.add(new PostalInfo(	6854	,"	Henne	"));
        list.add(new PostalInfo(	6855	,"	Outrup	"));
        list.add(new PostalInfo(	6857	,"	Blåvand	"));
        list.add(new PostalInfo(	6862	,"	Tistrup	"));
        list.add(new PostalInfo(	6870	,"	Ølgod	"));
        list.add(new PostalInfo(	6880	,"	Tarm	"));
        list.add(new PostalInfo(	6893	,"	Hemmet	"));
        list.add(new PostalInfo(	6900	,"	Skjern	"));
        list.add(new PostalInfo(	6920	,"	Videbæk	"));
        list.add(new PostalInfo(	6933	,"	Kibæk	"));
        list.add(new PostalInfo(	6940	,"	Lem St	"));
        list.add(new PostalInfo(	6950	,"	Ringkøbing	"));
        list.add(new PostalInfo(	6960	,"	Hvide Sande	"));
        list.add(new PostalInfo(	6971	,"	Spjald	"));
        list.add(new PostalInfo(	6973	,"	Ørnhøj	"));
        list.add(new PostalInfo(	6980	,"	Tim	"));
        list.add(new PostalInfo(	6990	,"	Ulfborg	"));
        list.add(new PostalInfo(	7000	,"	Fredericia	"));
        list.add(new PostalInfo(	7007	,"	Fredericia	"));
        list.add(new PostalInfo(	7029	,"	Fredericia	"));
        list.add(new PostalInfo(	7080	,"	Børkop	"));
        list.add(new PostalInfo(	7100	,"	Vejle	"));
        list.add(new PostalInfo(	7120	,"	Vejle Øst	"));
        list.add(new PostalInfo(	7130	,"	Juelsminde	"));
        list.add(new PostalInfo(	7140	,"	Stouby	"));
        list.add(new PostalInfo(	7150	,"	Barrit	"));
        list.add(new PostalInfo(	7160	,"	Tørring	"));
        list.add(new PostalInfo(	7171	,"	Uldum	"));
        list.add(new PostalInfo(	7173	,"	Vonge	"));
        list.add(new PostalInfo(	7182	,"	Bredsten	"));
        list.add(new PostalInfo(	7183	,"	Randbøl	"));
        list.add(new PostalInfo(	7184	,"	Vandel	"));
        list.add(new PostalInfo(	7190	,"	Billund	"));
        list.add(new PostalInfo(	7200	,"	Grindsted	"));
        list.add(new PostalInfo(	7250	,"	Hejnsvig	"));
        list.add(new PostalInfo(	7260	,"	Sønder Omme	"));
        list.add(new PostalInfo(	7270	,"	Stakroge	"));
        list.add(new PostalInfo(	7280	,"	Sønder Felding	"));
        list.add(new PostalInfo(	7300	,"	Jelling	"));
        list.add(new PostalInfo(	7321	,"	Gadbjerg	"));
        list.add(new PostalInfo(	7323	,"	Give	"));
        list.add(new PostalInfo(	7330	,"	Brande	"));
        list.add(new PostalInfo(	7361	,"	Ejstrupholm	"));
        list.add(new PostalInfo(	7362	,"	Hampen	"));
        list.add(new PostalInfo(	7400	,"	Herning	"));
        list.add(new PostalInfo(	7401	,"	Herning	"));
        list.add(new PostalInfo(	7429	,"	Herning	"));
        list.add(new PostalInfo(	7430	,"	Ikast	"));
        list.add(new PostalInfo(	7441	,"	Bording	"));
        list.add(new PostalInfo(	7442	,"	Engesvang	"));
        list.add(new PostalInfo(	7451	,"	Sunds	"));
        list.add(new PostalInfo(	7470	,"	Karup J	"));
        list.add(new PostalInfo(	7480	,"	Vildbjerg	"));
        list.add(new PostalInfo(	7490	,"	Aulum	"));
        list.add(new PostalInfo(	7500	,"	Holstebro	"));
        list.add(new PostalInfo(	7540	,"	Haderup	"));
        list.add(new PostalInfo(	7550	,"	Sørvad	"));
        list.add(new PostalInfo(	7560	,"	Hjerm	"));
        list.add(new PostalInfo(	7570	,"	Vemb	"));
        list.add(new PostalInfo(	7600	,"	Struer	"));
        list.add(new PostalInfo(	7620	,"	Lemvig	"));
        list.add(new PostalInfo(	7650	,"	Bøvlingbjerg	"));
        list.add(new PostalInfo(	7660	,"	Bækmarksbro	"));
        list.add(new PostalInfo(	7673	,"	Harboøre	"));
        list.add(new PostalInfo(	7680	,"	Thyborøn	"));
        list.add(new PostalInfo(	7700	,"	Thisted	"));
        list.add(new PostalInfo(	7730	,"	Hanstholm	"));
        list.add(new PostalInfo(	7741	,"	Frøstrup	"));
        list.add(new PostalInfo(	7742	,"	Vesløs	"));
        list.add(new PostalInfo(	7752	,"	Snedsted	"));
        list.add(new PostalInfo(	7755	,"	Bedsted Thy	"));
        list.add(new PostalInfo(	7760	,"	Hurup Thy	"));
        list.add(new PostalInfo(	7770	,"	Vestervig	"));
        list.add(new PostalInfo(	7790	,"	Thyholm	"));
        list.add(new PostalInfo(	7800	,"	Skive	"));
        list.add(new PostalInfo(	7830	,"	Vinderup	"));
        list.add(new PostalInfo(	7840	,"	Højslev	"));
        list.add(new PostalInfo(	7850	,"	Stoholm Jyll	"));
        list.add(new PostalInfo(	7860	,"	Spøttrup	"));
        list.add(new PostalInfo(	7870	,"	Roslev	"));
        list.add(new PostalInfo(	7884	,"	Fur	"));
        list.add(new PostalInfo(	7900	,"	Nykøbing M	"));
        list.add(new PostalInfo(	7950	,"	Erslev	"));
        list.add(new PostalInfo(	7960	,"	Karby	"));
        list.add(new PostalInfo(	7970	,"	Redsted M	"));
        list.add(new PostalInfo(	7980	,"	Vils	"));
        list.add(new PostalInfo(	7990	,"	Øster Assels	"));
        list.add(new PostalInfo(	8000	,"	Århus C	"));
        list.add(new PostalInfo(	8011	,"	Århus C	"));
        list.add(new PostalInfo(	8100	,"	Århus C	"));
        list.add(new PostalInfo(	8200	,"	Århus N	"));
        list.add(new PostalInfo(	8210	,"	Århus V	"));
        list.add(new PostalInfo(	8220	,"	Brabrand	"));
        list.add(new PostalInfo(	8229	,"	Risskov Ø	"));
        list.add(new PostalInfo(	8230	,"	Åbyhøj	"));
        list.add(new PostalInfo(	8240	,"	Risskov	"));
        list.add(new PostalInfo(	8245	,"	Risskov Ø	"));
        list.add(new PostalInfo(	8250	,"	Egå	"));
        list.add(new PostalInfo(	8260	,"	Viby J	"));
        list.add(new PostalInfo(	8270	,"	Højbjerg	"));
        list.add(new PostalInfo(	8300	,"	Odder	"));
        list.add(new PostalInfo(	8305	,"	Samsø	"));
        list.add(new PostalInfo(	8310	,"	Tranbjerg J	"));
        list.add(new PostalInfo(	8320	,"	Mårslet	"));
        list.add(new PostalInfo(	8330	,"	Beder	"));
        list.add(new PostalInfo(	8340	,"	Malling	"));
        list.add(new PostalInfo(	8350	,"	Hundslund	"));
        list.add(new PostalInfo(	8355	,"	Solbjerg	"));
        list.add(new PostalInfo(	8361	,"	Hasselager	"));
        list.add(new PostalInfo(	8362	,"	Hørning	"));
        list.add(new PostalInfo(	8370	,"	Hadsten	"));
        list.add(new PostalInfo(	8380	,"	Trige	"));
        list.add(new PostalInfo(	8381	,"	Tilst	"));
        list.add(new PostalInfo(	8382	,"	Hinnerup	"));
        list.add(new PostalInfo(	8400	,"	Ebeltoft	"));
        list.add(new PostalInfo(	8410	,"	Rønde	"));
        list.add(new PostalInfo(	8420	,"	Knebel	"));
        list.add(new PostalInfo(	8444	,"	Balle	"));
        list.add(new PostalInfo(	8450	,"	Hammel	"));
        list.add(new PostalInfo(	8462	,"	Harlev J	"));
        list.add(new PostalInfo(	8464	,"	Galten	"));
        list.add(new PostalInfo(	8471	,"	Sabro	"));
        list.add(new PostalInfo(	8472	,"	Sporup	"));
        list.add(new PostalInfo(	8500	,"	Grenaa	"));
        list.add(new PostalInfo(	8520	,"	Lystrup	"));
        list.add(new PostalInfo(	8530	,"	Hjortshøj	"));
        list.add(new PostalInfo(	8541	,"	Skødstrup	"));
        list.add(new PostalInfo(	8543	,"	Hornslet	"));
        list.add(new PostalInfo(	8544	,"	Mørke	"));
        list.add(new PostalInfo(	8550	,"	Ryomgård	"));
        list.add(new PostalInfo(	8560	,"	Kolind	"));
        list.add(new PostalInfo(	8570	,"	Trustrup	"));
        list.add(new PostalInfo(	8581	,"	Nimtofte	"));
        list.add(new PostalInfo(	8585	,"	Glesborg	"));
        list.add(new PostalInfo(	8586	,"	Ørum Djurs	"));
        list.add(new PostalInfo(	8592	,"	Anholt	"));
        list.add(new PostalInfo(	8600	,"	Silkeborg	"));
        list.add(new PostalInfo(	8620	,"	Kjellerup	"));
        list.add(new PostalInfo(	8632	,"	Lemming	"));
        list.add(new PostalInfo(	8641	,"	Sorring	"));
        list.add(new PostalInfo(	8643	,"	Ans By	"));
        list.add(new PostalInfo(	8653	,"	Them	"));
        list.add(new PostalInfo(	8654	,"	Bryrup	"));
        list.add(new PostalInfo(	8660	,"	Skanderborg	"));
        list.add(new PostalInfo(	8670	,"	Låsby	"));
        list.add(new PostalInfo(	8680	,"	Ry	"));
        list.add(new PostalInfo(	8700	,"	Horsens	"));
        list.add(new PostalInfo(	8721	,"	Daugård	"));
        list.add(new PostalInfo(	8722	,"	Hedensted	"));
        list.add(new PostalInfo(	8723	,"	Løsning	"));
        list.add(new PostalInfo(	8732	,"	Hovedgård	"));
        list.add(new PostalInfo(	8740	,"	Brædstrup	"));
        list.add(new PostalInfo(	8751	,"	Gedved	"));
        list.add(new PostalInfo(	8752	,"	Østbirk	"));
        list.add(new PostalInfo(	8762	,"	Flemming	"));
        list.add(new PostalInfo(	8763	,"	Rask Mølle	"));
        list.add(new PostalInfo(	8765	,"	Klovborg	"));
        list.add(new PostalInfo(	8766	,"	Nørre Snede	"));
        list.add(new PostalInfo(	8781	,"	Stenderup	"));
        list.add(new PostalInfo(	8783	,"	Hornsyld	"));
        list.add(new PostalInfo(	8800	,"	Viborg	"));
        list.add(new PostalInfo(	8830	,"	Tjele	"));
        list.add(new PostalInfo(	8831	,"	Løgstrup	"));
        list.add(new PostalInfo(	8832	,"	Skals	"));
        list.add(new PostalInfo(	8840	,"	Rødkærsbro	"));
        list.add(new PostalInfo(	8850	,"	Bjerringbro	"));
        list.add(new PostalInfo(	8860	,"	Ulstrup	"));
        list.add(new PostalInfo(	8870	,"	Langå	"));
        list.add(new PostalInfo(	8881	,"	Thorsø	"));
        list.add(new PostalInfo(	8882	,"	Fårvang	"));
        list.add(new PostalInfo(	8883	,"	Gjern	"));
        list.add(new PostalInfo(	8900	,"	Randers	"));
        list.add(new PostalInfo(	8950	,"	Ørsted	"));
        list.add(new PostalInfo(	8961	,"	Allingåbro	"));
        list.add(new PostalInfo(	8963	,"	Auning	"));
        list.add(new PostalInfo(	8970	,"	Havndal	"));
        list.add(new PostalInfo(	8981	,"	Spentrup	"));
        list.add(new PostalInfo(	8983	,"	Gjerlev J	"));
        list.add(new PostalInfo(	8990	,"	Fårup	"));
        list.add(new PostalInfo(	9000	,"	Aalborg	"));
        list.add(new PostalInfo(	9020	,"	Aalborg	"));
        list.add(new PostalInfo(	9029	,"	Aalborg	"));
        list.add(new PostalInfo(	9100	,"	Aalborg	"));
        list.add(new PostalInfo(	9200	,"	Aalborg SV	"));
        list.add(new PostalInfo(	9210	,"	Aalborg SØ	"));
        list.add(new PostalInfo(	9220	,"	Aalborg Øst	"));
        list.add(new PostalInfo(	9230	,"	Svenstrup J	"));
        list.add(new PostalInfo(	9240	,"	Nibe	"));
        list.add(new PostalInfo(	9260	,"	Gistrup	"));
        list.add(new PostalInfo(	9270	,"	Klarup	"));
        list.add(new PostalInfo(	9280	,"	Storvorde	"));
        list.add(new PostalInfo(	9293	,"	Kongerslev	"));
        list.add(new PostalInfo(	9300	,"	Sæby	"));
        list.add(new PostalInfo(	9310	,"	Vodskov	"));
        list.add(new PostalInfo(	9320	,"	Hjallerup	"));
        list.add(new PostalInfo(	9330	,"	Dronninglund	"));
        list.add(new PostalInfo(	9340	,"	Asaa	"));
        list.add(new PostalInfo(	9352	,"	Dybvad	"));
        list.add(new PostalInfo(	9362	,"	Gandrup	"));
        list.add(new PostalInfo(	9370	,"	Hals	"));
        list.add(new PostalInfo(	9380	,"	Vestbjerg	"));
        list.add(new PostalInfo(	9381	,"	Sulsted	"));
        list.add(new PostalInfo(	9382	,"	Tylstrup	"));
        list.add(new PostalInfo(	9400	,"	Nørresundby	"));
        list.add(new PostalInfo(	9430	,"	Vadum	"));
        list.add(new PostalInfo(	9440	,"	Aabybro	"));
        list.add(new PostalInfo(	9460	,"	Brovst	"));
        list.add(new PostalInfo(	9480	,"	Løkken	"));
        list.add(new PostalInfo(	9490	,"	Pandrup	"));
        list.add(new PostalInfo(	9492	,"	Blokhus	"));
        list.add(new PostalInfo(	9493	,"	Saltum	"));
        list.add(new PostalInfo(	9500	,"	Hobro	"));
        list.add(new PostalInfo(	9510	,"	Arden	"));
        list.add(new PostalInfo(	9520	,"	Skørping	"));
        list.add(new PostalInfo(	9530	,"	Støvring	"));
        list.add(new PostalInfo(	9541	,"	Suldrup	"));
        list.add(new PostalInfo(	9550	,"	Mariager	"));
        list.add(new PostalInfo(	9560	,"	Hadsund	"));
        list.add(new PostalInfo(	9574	,"	Bælum	"));
        list.add(new PostalInfo(	9575	,"	Terndrup	"));
        list.add(new PostalInfo(	9600	,"	Aars	"));
        list.add(new PostalInfo(	9610	,"	Nørager	"));
        list.add(new PostalInfo(	9620	,"	Aalestrup	"));
        list.add(new PostalInfo(	9631	,"	Gedsted	"));
        list.add(new PostalInfo(	9632	,"	Møldrup	"));
        list.add(new PostalInfo(	9640	,"	Farsø	"));
        list.add(new PostalInfo(	9670	,"	Løgstør	"));
        list.add(new PostalInfo(	9681	,"	Ranum	"));
        list.add(new PostalInfo(	9690	,"	Fjerritslev	"));
        list.add(new PostalInfo(	9700	,"	Brønderslev	"));
        list.add(new PostalInfo(	9740	,"	Jerslev J	"));
        list.add(new PostalInfo(	9750	,"	Østervrå	"));
        list.add(new PostalInfo(	9760	,"	Vrå	"));
        list.add(new PostalInfo(	9800	,"	Hjørring	"));
        list.add(new PostalInfo(	9830	,"	Tårs	"));
        list.add(new PostalInfo(	9850	,"	Hirtshals	"));
        list.add(new PostalInfo(	9870	,"	Sindal	"));
        list.add(new PostalInfo(	9881	,"	Bindslev	"));
        list.add(new PostalInfo(	9900	,"	Frederikshavn	"));
        list.add(new PostalInfo(	9940	,"	Læsø	"));
        list.add(new PostalInfo(	9970	,"	Strandby	"));
        list.add(new PostalInfo(	9981	,"	Jerup	"));
        list.add(new PostalInfo(	9982	,"	Ålbæk	"));
        list.add(new PostalInfo(	9990	,"	Skagen	"));
        list.add(new PostalInfo(	3900	,"	Nuuk	"));
        list.add(new PostalInfo(	3905	,"	Nuussuaq	"));
        list.add(new PostalInfo(	3910	,"	Kangerlussuaq	"));
        list.add(new PostalInfo(	3911	,"	Sisimiut	"));
        list.add(new PostalInfo(	3912	,"	Maniitsoq	"));
        list.add(new PostalInfo(	3913	,"	Tasiilaq	"));
        list.add(new PostalInfo(	3915	,"	Kulusuk	"));
        list.add(new PostalInfo(	3919	,"	Alluitsup Paa	"));
        list.add(new PostalInfo(	3920	,"	Qaqortoq	"));
        list.add(new PostalInfo(	3921	,"	Narsaq	"));
        list.add(new PostalInfo(	3922	,"	Nanortalik	"));
        list.add(new PostalInfo(	3923	,"	Narsarsuaq	"));
        list.add(new PostalInfo(	3924	,"	Ikerasassuaq	"));
        list.add(new PostalInfo(	3930	,"	Kangilinnguit	"));
        list.add(new PostalInfo(	3932	,"	Arsuk	"));
        list.add(new PostalInfo(	3940	,"	Paamiut	"));
        list.add(new PostalInfo(	3950	,"	Aasiaat	"));
        list.add(new PostalInfo(	3951	,"	Qasigiannguit	"));
        list.add(new PostalInfo(	3952	,"	Ilulissat	"));
        list.add(new PostalInfo(	3953	,"	Qeqertarsuaq	"));
        list.add(new PostalInfo(	3955	,"	Kangaatsiaq	"));
        list.add(new PostalInfo(	3961	,"	Uummannaq	"));
        list.add(new PostalInfo(	3962	,"	Upernavik	"));
        list.add(new PostalInfo(	3964	,"	Qaarsut	"));
        list.add(new PostalInfo(	3970	,"	Pituffik	"));
        list.add(new PostalInfo(	3971	,"	Qaanaaq	"));
        list.add(new PostalInfo(	3980	,"	Ittoqqortoormiit	"));
        list.add(new PostalInfo(	3984	,"	Danmarkshavn	"));
        list.add(new PostalInfo(	3985	,"	Constable Pynt	"));
        
        
        Connection connection = null;
        try
        {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/lovestruck?serverTimezone=UTC","gruppe10","gruppe10");
            // jdbc:mysql://localhost/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            
            
        } catch(SQLException throwables)
        {
            throwables.printStackTrace();
        }
        
        for(PostalInfo postalInfo : list)
        {
            addPostalInfoToDatabase(postalInfo, connection);
        }
        
    }
    private static void addPostalInfoToDatabase(PostalInfo postalInfo, Connection connection)
    {
        try
        {
            //Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/dummy_lovestruck","gruppe10","gruppe10");
            System.out.println("TEST1");
            
            String sqlCommand = "INSERT into postal_info(zip_code, city) values (?,?);";
            
            
            // det er vores SQL sætning som vi beder om at få prepared til at blive sendt til databasen:
            PreparedStatement preparedStatement = connection.prepareStatement(sqlCommand);
            preparedStatement.setInt(1, postalInfo.getZipCode());
            preparedStatement.setString(2, postalInfo.getCity());
            System.out.println(preparedStatement);
            preparedStatement.executeUpdate();
        }
        catch(SQLException e)
        {
            System.out.println("Error in addPostalInfoToDatabase: " + e.getMessage());
            
        }
        
    }
    
    
    
}
